language: go

os:
    - linux

go:
    - 1.15.x

script: make validate

before_install:
    - if [ "$TRAVIS_OS_NAME" == "linux" ]; then
        sudo apt-get update -y;
        sudo apt-get install libxi-dev libxinerama-dev libxcursor-dev libxrandr-dev libgl1-mesa-dev -y;
      fi

before_script:
    - GO111MODULE=off go get -u golang.org/x/lint/golint
